import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { ArrowRight, LockKeyhole, Mail, UserRound } from 'lucide-react';
import api from '../services/api';
import { useAuth } from '../context/AuthContext';

export default function AuthPage({ mode }) {
  const isSignup = mode === 'signup'; const navigate = useNavigate(); const { authenticate } = useAuth();
  const [form, setForm] = useState({ name: '', email: '', password: '', confirmPassword: '' }); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const change = event => setForm(current => ({ ...current, [event.target.name]: event.target.value }));
  async function submit(event) { event.preventDefault(); setError(''); if (isSignup && form.password !== form.confirmPassword) return setError('Passwords do not match.'); setBusy(true); try { const { data } = await api.post(`/auth/${isSignup ? 'signup' : 'login'}`, form); authenticate(data); navigate('/dashboard'); } catch (err) { setError(err.response?.data?.message || 'We could not connect. Please try again.'); } finally { setBusy(false); } }
  return <main className="auth-page"><section className="auth-promo"><a className="brand" href="/"><span>l</span>learniee</a><div><p className="eyebrow">LEARNING, MADE PERSONAL</p><h1>Small steps today.<br />Big possibilities tomorrow.</h1><p>Thoughtful courses and inspiring teachers, all in one calm place for your family.</p></div><small>© 2025 Learniee</small></section><section className="auth-form-wrap"><form className="auth-form" onSubmit={submit}><div><p className="eyebrow">WELCOME {isSignup ? 'TO LEARNIEE' : 'BACK'}</p><h2>{isSignup ? 'Create your parent account' : 'Sign in to your account'}</h2><p>{isSignup ? 'Start finding courses your child will love.' : 'Continue your child’s learning journey.'}</p></div>{isSignup && <label>Full name<div className="input-wrap"><UserRound size={17}/><input name="name" value={form.name} onChange={change} placeholder="Your full name" required /></div></label>}<label>Email address<div className="input-wrap"><Mail size={17}/><input name="email" value={form.email} onChange={change} type="email" placeholder="you@example.com" required /></div></label><label>Password<div className="input-wrap"><LockKeyhole size={17}/><input name="password" value={form.password} onChange={change} type="password" minLength="8" placeholder="At least 8 characters" required /></div></label>{isSignup && <label>Confirm password<div className="input-wrap"><LockKeyhole size={17}/><input name="confirmPassword" value={form.confirmPassword} onChange={change} type="password" placeholder="Repeat your password" required /></div></label>}{error && <p className="form-error">{error}</p>}<button className="auth-submit" disabled={busy}>{busy ? 'Please wait…' : isSignup ? 'Create account' : 'Sign in'} <ArrowRight size={17}/></button><p className="auth-switch">{isSignup ? 'Already have an account?' : 'New to Learniee?'} <Link to={isSignup ? '/login' : '/signup'}>{isSignup ? 'Sign in' : 'Create an account'}</Link></p></form></section></main>;
}
